### ISSUE TITLE
Scrum Reports On Monday Should Print Fridays Work

### ISSUE THREAD

**Issue by ancbro** [ancbro/time-management#16]
The Scrum option prints notes and tasks from the previous day (known at the time of writing) for reflection during scrum / standup. On Monday's we should print Friday's work, rather than Sundays. This will no doubt undergo further enhancements as needed.

**Comment by Straywind** [comment]
Should it still print yesterdays work for weekends? i.e. On Sunday print Saturdays work and Saturday print Fridays work? If so, a simple if/else statement will do it (I think), otherwise it will need a couple other conditions.

Also, maybe Monday should print BOTH Friday AND Sundays work and then print which was Fridays and which was Sundays?

**Comment by Straywind** [comment]
I went ahead and implemented Monday showing Friday's results. It just ignores Sunday, but it can always be modified in the future if need be.
