### ISSUE TITLE
Return to previous menu

### ISSUE THREAD

**Issue by Straywind** [ancbro/time-management#33]
There seems to be no way to return back to the previous menu. e.g. If you select TM, you cannot return back to the main menu. Similarly, if you select a task in TM, you cannot return back to the TM menu without completing the task. This is irritating if you accidentally selected the wrong option.

I would be quite happy to have a go at adding in a "return" option in each menu/task. It would make it a lot more testing friendly at the least.

**Comment by ancbro** [comment]
You are correct and you are more than welcome to have a go. Just a heads up, I added a [pre-commit](https://pre-commit.com/) hook for formatting with [Black](https://pypi.org/project/black/). Let me know if it causes any trouble. [Flake8](https://flake8.pycqa.org/en/latest/) is what I am using for linting. I'll get this stuff in the README sooner or later.

**Comment by ancbro** [comment]
I updated the [contribution guide](https://github.com/ancbro/time-management/blob/master/CONTRIBUTING.md) to include further information about the standards the project hopes to adhere to. Please follow up with any questions or concerns. Thanks!

**Comment by Straywind** [comment]
I'll finish this up once I find out if you're ok with my solution or not.

Hopefully the formatting and linting is correct this time around ;)

**Comment by ancbro** [comment]
Lol - no worries on the formatting. I make a big deal about it just because it's hard to review PRs that have lots of non-functional changes as a result of reformatting. 

I added a comment to your PR that reflects my thoughts and also pushed a demonstration about the route I would take. Let me know what you think.

Thanks for opening this issue. It is nice to see things become a bit more cohesive.
