### ISSUE TITLE
Entire application needs commenting

### ISSUE THREAD

**Issue by Straywind** [ancbro/time-management#50]
Comments should be written out before any actual coding takes place, and the application as it is has not a single line of comment.

Ideally, someone should go through the entire program and add comments wherever they should be present. Perhaps it would be easier to divide each individual file up into a ticket?

Additionally, commenting should become standard practice as we go forward.

**Comment by ancbro** [comment]
Comments have their place, but on the whole I agree with the following: https://blog.usejournal.com/stop-writing-code-comments-28fef5272752. 

If documentation beyond the code itself is needed, Docstrings I think are preferable: https://www.python.org/dev/peps/pep-0257/#:~:text=A%20docstring%20is%20a%20string,module%20should%20also%20have%20docstrings.

**Comment by Straywind** [comment]
That makes me want to cry, but it's up to you :)

**Comment by Capm96** [comment]
😆 how come? I think its good to focus on writing code that can be understood without comments, and let the comments be used only when really nescessary.

**Comment by Straywind** [comment]
Because when I learned programming, it was drummed into me hard to comment constantly. Every module, every class, every method and every function. I'm not against  this method, but it's just ugly to my eyes.

**Comment by Capm96** [comment]
I think that is a good habit to have. Documenting is so important, especially as the application grows. I just think that the amount of commenting you mentioned wouldn't be so beneficial for us at the moment since a lot of our methods are quite small, which could make the comments a bit redudant. I'm all for increased commenting moving forward though, especially on more complicated methods / variables which are not so clear.

**Comment by Straywind** [comment]
Even if some commenting is redundant, it makes it consistent and ensures
you don't forget when it really is needed. It is also so easy to think "Oh,
it's really obvious what this does" when you first write it, but it may not
be so obvious when the next guy comes around, or yourself in 3 months.

**Comment by ancbro** [comment]
@Straywind 

> Because when I learned programming, it was drummed into me hard to comment constantly. Every module, every class, every method and every function. I'm not against this method, but it's just ugly to my eyes.

So maybe five years ago I took a Python course, and my instructor said the same thing. Then I read [Clean Code](https://github.com/SaikrishnaReddy1919/MyBooks/blob/master/%5BPROGRAMMING%5D%5BClean%20Code%20by%20Robert%20C%20Martin%5D.pdf) and I got a totally different picture. 

I think part of this issue is historical, and indeed my instructor was in industry way back in the day before he switched to academia. It USED to be the case that there was a limited amount of characters one could use to define a function or variable in a given language - well before Java I should say. At that time I suspect robust comments were of great use. Today we have languages where memory is predominantly a non-issue, and one can write self-documenting code to their hearts content.

**Comment by ancbro** [comment]
@AyushRawal You've done some nice work for this project. Thanks again. Any thoughts on the conversation here?

**Comment by AyushRawal** [comment]
I'll surely take a look at it. I guess it won't take much time. But I have my exams coming up and I'll be busy for about 2 weeks. Think it can wait a while?
And btw, I also think that the code at this stage is self-explanatory, but maybe it should be documented if the project expands further in future.
